# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vEvToBS2pwQUBSy9ZnO9P8dN0XSWYwf
"""

import pandas as pd
import gradio as gr

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier


# =====================================
# STEP 1 : LOAD DATA
# =====================================

df = pd.read_csv(
    "finance_fraud_data.csv"
)


# =====================================
# STEP 2 : PREPROCESSING
# =====================================

df["Timestamp"] = pd.to_datetime(
    df["Timestamp"]
)

df["Hour"] = df[
    "Timestamp"
].dt.hour


encoder = LabelEncoder()


for col in [

    "Merchant_Category",
    "Device_Type"

]:

    df[col] = encoder.fit_transform(
        df[col]
    )


df["Spending_Ratio"] = (

    df["Amount"] /

    (df["Avg_Spending_Habit"] + 1)

)


# =====================================
# STEP 3 : ML MODEL
# =====================================

features = [

    "Amount",

    "Merchant_Category",

    "Distance_from_Home",

    "Device_Type",

    "IP_Risk_Score",

    "Avg_Spending_Habit",

    "Is_Weekend",

    "Is_Night_Transaction",

    "Hour",

    "Spending_Ratio"

]


X = df[features]

y = df["Is_Fraud"]


model = RandomForestClassifier(
    random_state=42
)

model.fit(
    X,
    y
)


# =====================================
# STEP 4 : FUZZY
# =====================================

def high(x, a, b):

    if x <= a:
        return 0

    elif x >= b:
        return 1

    else:
        return (x-a)/(b-a)


# =====================================
# STEP 5 : USER APP
# =====================================

def protect_user(

    amount,
    recipient

):

    # backend features
    merchant = 1
    distance = 50
    device = 1
    ip_risk = 0.6
    avg_spending = 3000
    weekend = 0
    night = 1
    hour = 23

    spending_ratio = (
        amount /
        (avg_spending + 1)
    )


    input_df = pd.DataFrame([{

        "Amount": amount,

        "Merchant_Category": merchant,

        "Distance_from_Home": distance,

        "Device_Type": device,

        "IP_Risk_Score": ip_risk,

        "Avg_Spending_Habit": avg_spending,

        "Is_Weekend": weekend,

        "Is_Night_Transaction": night,

        "Hour": hour,

        "Spending_Ratio": spending_ratio

    }])


    # =========================
    # ML PREDICTION
    # =========================

    ml_probability = model.predict_proba(
        input_df
    )[0][1]


    # =========================
    # FUZZY AI
    # =========================

    ml_high = high(
        ml_probability,
        0.4,
        0.8
    )

    amount_high = high(
        amount,
        500,
        5000
    )

    ip_high = high(
        ip_risk,
        0.4,
        0.8
    )


    fuzzy_score = (

        ml_high +

        amount_high +

        ip_high

    ) / 3


    # =========================
    # CUSTOMER DECISION
    # =========================

    if fuzzy_score < 0.4:

        return f"""
        <div style='padding:20px;
        background:#d4edda;
        border-radius:15px;
        text-align:center;'>

        <h2>🟢 Transaction Safe</h2>

        <p>
        ML Risk: {round(ml_probability,2)}
        </p>

        <p>
        AI Score: {round(fuzzy_score,2)}
        </p>

        </div>
        """


    elif fuzzy_score < 0.7:

        return f"""
        <div style='padding:20px;
        background:#fff3cd;
        border-radius:15px;
        text-align:center;'>

        <h2>🟡 Verification Required</h2>

        <p>
        ML Risk: {round(ml_probability,2)}
        </p>

        <p>
        AI Score: {round(fuzzy_score,2)}
        </p>

        <p>
        OTP required.
        </p>

        </div>
        """


    else:

        return f"""
        <div style='padding:20px;
        background:#f8d7da;
        border-radius:15px;
        text-align:center;'>

        <h2>🔴 Transaction Blocked</h2>

        <p>
        ML Risk: {round(ml_probability,2)}
        </p>

        <p>
        AI Score: {round(fuzzy_score,2)}
        </p>

        <p>
        Contact bank support.
        </p>

        </div>
        """


# =====================================
# UI
# =====================================

demo = gr.Interface(

    fn=protect_user,

    inputs=[

        gr.Number(
            label="💰 Amount"
        ),

        gr.Text(
            label="👤 Recipient"
        )

    ],

    outputs=[

        gr.HTML()

    ],

    title=(
        "🏦 Smart Payment Protection"
    )

)


demo.launch()

